# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: CV
    url: 'cv/'
    weight: 20
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Teaching
    url: '#teaching'
    weight: 50
  - name: Posts
    url: '#posts'
    weight: 60
  - name: Tech
    url: 'tech/'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
